### ISSUE TITLE
Consider reverting 0.12.4

### ISSUE THREAD

**Issue by odow** [jump-dev/ECOS.jl#123]
@blegat 0.12.4 should have been a breaking release since it no longer supports the ExponentialCone and it bumped to MOI 0.10. 

Can we consider yanking the 0.12.4 release from the General registry? Then we can fix https://github.com/jump-dev/MathOptInterface.jl/pull/1592, and properly update the tests etc before tagging 0.13.0.

**Comment by blegat** [comment]
Indeed, +1 for doing that.

**Comment by odow** [comment]
Yanked in General: https://github.com/JuliaRegistries/General/pull/49565
