### ISSUE TITLE
Negative gaps and inaccurate optimal values when the solutions are suboptimal

### ISSUE THREAD

**Issue by SamZhou1996** [jump-dev/ECOS.jl#54]
While using ECOS to solve a convex programming problem, I noticed that when the solution status is :Suboptimal, it returns a primal-dual pair that has a negative duality gap. Attached is an example of such a situation, where [solve!()](https://github.com/JuliaOpt/Convex.jl/blob/master/src/solution.jl) and [conic_problem!()](https://github.com/JuliaOpt/Convex.jl/blob/master/src/problems.jl) are called from Convex.jl.

![screen shot 2017-09-08 at 18 25 21](https://user-images.githubusercontent.com/29708854/30233363-2d2f8410-94c3-11e7-959a-93e69c42e404.png)

**Comment by SamZhou1996** [comment]
It turns out that the gap between the optimal value and the evaluation of the objective function using the optimal solution is caused by Convex.jl, so ECOS is doing fine on this.

**Comment by odow** [comment]
Closing as stale. We now have better status reporting mechanisms.
