### ISSUE TITLE
Occasional segfault on 64-bit windows, Julia 1.0

### ISSUE THREAD

**Issue by mlubin** [jump-dev/ECOS.jl#77]
https://ci.appveyor.com/project/JuliaOpt/ecos-jl/build/1.0.63/job/55m6ej3fxqoony62
https://ci.appveyor.com/project/JuliaOpt/ecos-jl/build/1.0.69/job/8ipce82asa3m2q38

**Comment by odow** [comment]
Closing as stale. We obviously haven't noticed any recently.
