### ISSUE TITLE
Add support for VariablePrimalStart and ConstraintDualStart

### ISSUE THREAD

**Issue by blegat** [jump-dev/ECOS.jl#79]
See https://github.com/JuliaOpt/JuMP.jl/issues/1554

**Comment by blegat** [comment]
Yes, ECOS is missing a PR like https://github.com/JuliaOpt/SCS.jl/pull/111. Once it's done, a code that currently gets this error will just work.

**Comment by odow** [comment]
Closing because this isn't supported by the upstream solver. See https://github.com/embotech/ecos/issues/87
