### ISSUE TITLE
ConstraintPrimal is supposed to return value of function at result point

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/ECOS.jl#81]
it should not be returning a constant given by the set.
see http://www.juliaopt.org/MathOptInterface.jl/dev/apireference/#MathOptInterface.ConstraintPrimal

e.g. see https://github.com/JuliaOpt/ECOS.jl/blob/77eaa92ea05c513099db2b0fff9f23513ae78b79/src/MOIWrapper.jl#L335
the set is Zeros, and the constraint primal returned is just zero. but the value of the constraint function is likely numerically non-zero.

**Comment by blegat** [comment]
This was not part of the API so I used the set constant. Now that there are result fallback in MOIU we can use that
